# Generated by Django 6.0.7 on 2026-07-18 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_limit', models.FloatField(help_text='Límite máximo permitido')),
                ('current_value', models.FloatField(default=0.0, help_text='Valor actual consumido')),
                ('unit', models.CharField(help_text='Unidad de medida, ej. GB, USD', max_length=20)),
                ('cutoff_date', models.DateField(help_text='Fecha en que se reinicia el consumo')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.department')),
            ],
        ),
    ]
