# Generated by Django 6.0.7 on 2026-07-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='metric_type',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], default='ingreso', help_text='Tipo de métrica: ingreso o egreso', max_length=10),
        ),
    ]
